import cv2 as cv

round_img = cv.imread('img/rounds/test19.png')

chars = [
  (1, 'shunei'),
  (2, 'meitenkun'),
  (3, 'benimaru'),
  (4, 'iori'),
  (5, 'joe'),
  (6, 'kyo'),
  (7, 'chizuru'),
  (8, 'andy'),
  (9, 'yuri'),
  (10, 'terry'),
  (11, 'yashiro'),
  (12, 'king'),
  (13, 'mai'),
  (14, 'shermie'),
  (15, 'chris'),
  (17, 'robert'),
  (18, 'leona'),
  (19, 'ralf'),
  (20, 'clark'),
  (21, 'bluemary'),
  (22, 'luong'),
  (23, 'vanessa'),
  (24, 'ramon'),
  (25, 'dinosaur'),
  (26, 'athena'),
  (27, 'antonov'),
  (28, 'ash'),
  (29, 'kukri'),
  (30, 'isla'),
  (31, 'k'),
  (33, 'dolores'),
  (35, 'angel'),
  (36, 'krohnen'),
  (37, 'maxima'),
  (38, 'kula'),
  (39, 'elisabeth'),
  (40, 'rock'),
  (42, 'gato'),
]